version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: spotify_data
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/spotify_data
      - ./data:/csvdata